### PR TITLE
fixed IndexBuffer type(16bit -> 32 bit) for DX11 port

### PR DESCRIPTION
**Pull request by bagobor**
Now works fine! Orig. version leads to DX debug guards.
Btw: NICE work! it works faster and with less CPU load then GL version!

### CODE REVIEW

**Comment by cmaughan** [comment]
Is this simply to avoid the case where we spill out over the end of the buffer?  I had been intending to fix this more intelligently and detecting that case; but your fix will do for now!

**Comment by cmaughan** [comment]
Also, I've done no optimization on this code; but it works well so far :) I suspect there are ways it could be improved, but it's a while since I played.  Probably due an update from the master version too...

**Comment by bagobor** [comment]
anyway, it's now 50% less CPU load (more for debug build) than GL version.
:D

**Comment by cmaughan** [comment]
Good to know it is quick; I suspected it might be!

**Comment by bagobor** [comment]
Did you notice some bad perfomance code in original GL code or it was
implementation from scratch?

**Comment by cmaughan** [comment]
Mostly it was a port of the original source; VB usage is the thing you have to get right - using the locking flags correctly to ensure that you are writing to part of the buffer while the GPU is consuming the rest, and making sure you only write to fast memory, etc.

**Pull request merged**
